# coding: utf-8

"""
    Compass SDK

    API for interacting with Cohere's Compass

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cohere.compass.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_datasource(self) -> None:
        """Test case for create_datasource

        Create a new datasource
        """
        pass

    def test_delete_datasource(self) -> None:
        """Test case for delete_datasource

        Delete a datasource by ID
        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Get the configuration schema for a specific config type
        """
        pass

    def test_get_datasource(self) -> None:
        """Test case for get_datasource

        Get a datasource by ID
        """
        pass

    def test_list_configs(self) -> None:
        """Test case for list_configs

        List all available config types
        """
        pass

    def test_list_datasources(self) -> None:
        """Test case for list_datasources

        List all datasources
        """
        pass


if __name__ == '__main__':
    unittest.main()
