# coding: utf-8

"""
    Compass SDK

    API for interacting with Cohere's Compass

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cohere.compass.models.get_config_response import GetConfigResponse

class TestGetConfigResponse(unittest.TestCase):
    """GetConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConfigResponse:
        """Test GetConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConfigResponse`
        """
        model = GetConfigResponse()
        if include_optional:
            return GetConfigResponse(
                config_schema = None,
                auth_url = ''
            )
        else:
            return GetConfigResponse(
        )
        """

    def testGetConfigResponse(self):
        """Test GetConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
