# coding: utf-8

"""
    Compass SDK

    API for interacting with Cohere's Compass

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cohere.compass.models.azure_blob_storage_config import AzureBlobStorageConfig

class TestAzureBlobStorageConfig(unittest.TestCase):
    """AzureBlobStorageConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AzureBlobStorageConfig:
        """Test AzureBlobStorageConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AzureBlobStorageConfig`
        """
        model = AzureBlobStorageConfig()
        if include_optional:
            return AzureBlobStorageConfig(
                type = 'msft_azure_blob_storage',
                connection_string = '',
                container_name = '',
                name_starts_with = ''
            )
        else:
            return AzureBlobStorageConfig(
        )
        """

    def testAzureBlobStorageConfig(self):
        """Test AzureBlobStorageConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
