# coding: utf-8

"""
    Compass SDK

    API for interacting with Cohere's Compass

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cohere.compass.models.paginated_list_data_source import PaginatedListDataSource

class TestPaginatedListDataSource(unittest.TestCase):
    """PaginatedListDataSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedListDataSource:
        """Test PaginatedListDataSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedListDataSource`
        """
        model = PaginatedListDataSource()
        if include_optional:
            return PaginatedListDataSource(
                value = [
                    cohere.compass.models.data_source.DataSource(
                        id = '', 
                        name = '', 
                        description = '', 
                        config = null, 
                        destinations = [
                            ''
                            ], 
                        enabled = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_token = ''
            )
        else:
            return PaginatedListDataSource(
        )
        """

    def testPaginatedListDataSource(self):
        """Test PaginatedListDataSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
