name: Formatting

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install requirements
        run: |
          pip install pre-commit

      - name: Formatting
        run: |
          pre-commit run --all-files
